# Generated by Django 5.0.4 on 2024-05-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
