# Generated by Django 5.0.4 on 2024-05-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
